name: CI
on: 
  pull_request:
    branches: [develop]

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
      - uses: actions/checkout@v3
      - name: Use NodeJS 
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run prettier --check "**/*.js"
      - run: npm test
      - run: npm run test -- --coverage
        env:
          CI: true
          
         